export const skillsData = [
 "HTML5",
 "CSS",
 "Tailwind CSS",
 "JavaScript",
 "TypeScript",
 "React.js",
 "Redux Toolkit",
 "Node.js",
 "Express.js",
 "MongoDB",
 "API Integration",
 "AI Integration",
 "Git",
 "Debugging",
 "Research Skills",
 "Visual Studio Code",
 "Microsoft Office",
];
